# Generated by Django 5.2.7 on 2025-12-30 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guestapp', '0002_tbl_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_jobpost',
            fields=[
                ('jobpost_id', models.AutoField(primary_key=True, serialize=False)),
                ('requirement', models.TextField()),
                ('cutoff_mark', models.FloatField()),
                ('post_date', models.DateField(auto_now_add=True)),
                ('application_end_date', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_company')),
            ],
        ),
    ]
