# Generated by Django 5.2.7 on 2025-12-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_jobpost',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
