# Generated by Django 5.2.7 on 2025-12-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_year', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
