# Generated by Django 5.2.7 on 2025-12-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_tbl_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
    ]
