# Generated by Django 5.2.7 on 2025-12-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_tbl_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_classtype',
            fields=[
                ('classtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('classtype_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
