# Generated by Django 5.2.7 on 2025-12-11 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_department')),
            ],
        ),
    ]
