# Generated by Django 5.2.7 on 2025-12-15 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_tbl_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_trainingclass',
            fields=[
                ('trainingclass_id', models.AutoField(primary_key=True, serialize=False)),
                ('trainingclass_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_batch')),
                ('classtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_classtype')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_course')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_location')),
            ],
        ),
    ]
