# Generated by Django 5.2.7 on 2025-12-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_tbl_trainingclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_trainingclass',
            name='location_id',
        ),
    ]
