# Generated by Django 5.2.7 on 2026-01-09 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_tbl_trainingclass_location_id'),
        ('companyapp', '0002_tbl_jobpost_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_requests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('student_count', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_batch')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_course')),
                ('jobpost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.tbl_jobpost')),
            ],
        ),
    ]
