# Generated by Django 5.2.7 on 2026-01-14 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_tbl_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_interview_schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_date', models.DateField()),
                ('stage', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_requests')),
            ],
        ),
    ]
