# Generated by Django 5.2.7 on 2026-01-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_tbl_interview_schedule'),
        ('guestapp', '0003_tbl_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_schedule',
            fields=[
                ('studentschedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_requests')),
                ('schedule_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_interview_schedule')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_student')),
            ],
        ),
    ]
