# Generated by Django 5.2.7 on 2026-01-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_student_schedule'),
        ('guestapp', '0003_tbl_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_schedule',
            new_name='tbl_student_schedule',
        ),
    ]
