# Generated by Django 5.2.7 on 2025-12-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_tbl_trainingclass_location_id'),
        ('guestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('company_logo', models.ImageField(upload_to='')),
                ('contact_number', models.BigIntegerField()),
                ('contact_email', models.CharField(max_length=50)),
                ('id_proof', models.ImageField(upload_to='')),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_location')),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_login')),
            ],
        ),
    ]
