# Generated by Django 5.2.7 on 2026-01-05 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_tbl_trainingclass_location_id'),
        ('guestapp', '0002_tbl_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='')),
                ('id_proof', models.ImageField(upload_to='')),
                ('mark', models.FloatField()),
                ('percentage', models.FloatField()),
                ('photo', models.ImageField(upload_to='')),
                ('reg_id', models.DateField(auto_now_add=True)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('contact_number', models.BigIntegerField()),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_batch')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_course')),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_login')),
            ],
        ),
    ]
